### ISSUE TITLE
ModuleNotFoundError: No module named 'Code'

### ISSUE THREAD

**Issue by tejase** [tuyanglin/Fingerprint-Restoration#1]
Steps to reproduce:
I tried importing the code in google colab, and followed the same steps in the README.

I get " **ModuleNotFoundError: No module named 'Code'** " when i run "python preprocess.py imagepath outputpath" command.

**Comment by tuyanglin** [comment]
You may need to change the import module path in preprocess.py.
The source file is as follows, where "Code" is the root directory, perhaps you can change the corresponding path to ensure that it is imported properly.
`from Code.preprocessing.add_noise import add_img_noise
from Code.preprocessing.nor import normalize
from Code.preprocessing.gabor import gabor_enhance
from Code.preprocessing.thining import make_thin`
